# -*- coding: utf-8 -*-
"""untitled12.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/gist/wissalelkhaoulani/a74910c7da2e2f07c41e9c4a1f2006f8/untitled12.ipynb
"""

pip install ucimlrepo

from ucimlrepo import fetch_ucirepo

# fetch dataset
iris = fetch_ucirepo(id=53)

# data (as pandas dataframes)
X = iris.data.features
y = iris.data.targets

# metadata
print(iris.metadata)

# variable information
print(iris.variables)

import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

# Combine features (X) and targets (y) into a single DataFrame for easier plotting
iris_df = pd.concat([X, y], axis=1)

# Rename the target column to 'species' for better readability in plots
iris_df = iris_df.rename(columns={'class': 'species'})

# Create a pair plot to visualize relationships between features, colored by species
sns.pairplot(iris_df, hue='species', diag_kind='kde')
plt.suptitle('Pair Plot of Iris Dataset Features by Species', y=1.02) # Add a title above the subplots
plt.show()

"""This pair plot displays scatter plots for each pair of features and a kernel density estimate (KDE) plot for each feature's distribution. The points are colored according to the 'species' of the iris plant, allowing us to visually inspect the separation of the different classes based on their features."""